name:                queryparser
version:             0.1.0.0
github:              "turanct/queryparser"
license:             BSD3
author:              "Toon Daelman"
maintainer:          "spinnewebber_toon@hotmail.com"
copyright:           "2021 Toon Daelman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/queryparser#readme>

dependencies:
- base >= 4.7 && < 5
- parser-combinators >= 1.2 && < 2
- megaparsec >= 9.0 && < 10
library:
  source-dirs: src

executables:
  queryparser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - queryparser

tests:
  queryparser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - queryparser
